// src/app/layout.tsx

import type { Metadata } from "next";
// 1. next/font/google에서 사용할 폰트를 import 합니다.
import { Inter, Libre_Baskerville } from "next/font/google"; 
import "./globals.css";

// 2. Inter 폰트는 예시이며, 필요 없다면 지워도 됩니다.
const inter = Inter({ subsets: ["latin"] });

// 3. Libre Baskerville 폰트를 설정합니다.
//    - weight: 사용할 폰트 굵기 (400=normal, 700=bold)
//    - subsets: 언어 범위 (보통 'latin'을 사용)
//    - variable: Tailwind CSS와 연동하기 위한 CSS 변수 이름
const libreBaskerville = Libre_Baskerville({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-libre-baskerville", // CSS 변수 이름 지정
});

export const metadata: Metadata = {
  title: "J&J Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 4. <html> 태그의 className에 폰트 변수를 추가합니다.
    <html lang="en" className={`${libreBaskerville.variable}`}>
      <body>{children}</body>
    </html>
  );
}